version: "3.6"
services:
  postgres_15:
    image: postgres:15
    container_name: postgres15
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
