version: "3.6"
services:
  postgres_12:
    image: postgres:12
    container_name: postgres12
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PG_VOLUME_PATH}:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
